### ISSUE TITLE
Collision handling

### ISSUE THREAD

**Issue by KosBar49** [LoRaMesher/LoRaMesher#20]
Hi @Jaimi5, I wonder how the collision mechanism is implemented in your work, what will happen if two nodes will start to send the messages? As I see in the examples we only broadcast the message from one node to others but what about taking care of passing it to the rest of the network? It there any option to use the nodes in receiver/transmitter mode?

**Comment by Jaimi5** [comment]
Hi @KosBar49!  You can see how the collision mechanism for a single message is working at the following link: [IEEE](https://ieeexplore.ieee.org/document/9930341). We implemented a Carrier Sense Multiple Access / Collision Avoidance (CSMA/CA). In the next iteration, it will be implemented a reliable connection with resend if a collision occurs. 

> As I see in the examples we only broadcast the message from one node to others but what about taking care of passing it to the rest of the network?

At this moment, there is no implementation to forward a broadcast message to all the networks. There is an initial concept about it, but it is not fully implemented yet.


> It there any option to use the nodes in receiver/transmitter mode?

At this moment, no.

If you have any questions, do not hesitate!
