### ISSUE TITLE
Add library properties file please

### ISSUE THREAD

**Issue by wreutz** [LoRaMesher/LoRaMesher#23]
Hi,

I'm using `arduino-cli` and when I try to install from command line using GitHub url it throws an error. After manually adding it to my library folder and listing the installed packages it is missing.

Found the problem:

the project provides an library.json file but the library.properties file is missing. I created one and then it is showing in the `arduino-cli lib list` command. Could you please add the file to the repository?

```
name=LoRaMesher
version=0.0.6
author=Joan Miquel Solé
maintainer=Joan Miquel Solé
sentence=A mesh network for LoRa.
paragraph=The LoRaMesher library implements a distance-vector routing protocol for communicating messages among LoRa nodes.
category=Communication
url=https://github.com/LoRaMesher/LoRaMesher
architectures=*
includes=LoRaMesher.h
depends=RadioLib (>=5.6.0),ArduinoLog
```

cheers!

**Comment by Jaimi5** [comment]
Thanks for the information! 
A new version has been upload that includes the library.properties

Hope this library is helping you!
