### ISSUE TITLE
Need an example of transferring small files using LoraMesher (<80kb)

### ISSUE THREAD

**Issue by Xanuman** [LoRaMesher/LoRaMesher#53]
I'm an inexperienced programmer and just started to understand the LoRaMesher library.
My task is to send an image from a device based on ESP32-CAM and LoRa Ra-01 module. The receiver is ESP32 WROOM 32 + Ra-01

Image size does not exceed 80 kilobytes

Is there somewhere a simple example of transferring an image using LoRaMesher?

**Comment by Jaimi5** [comment]
Hi @Xanuman 
You have an example on how to send large data using LoRaMesher in the following link: [LargeAndReliablePayload](https://github.com/LoRaMesher/LoRaMesher/tree/main/examples/LargePayload)

I hope this helps!
Anything else that I can help you with?

Jan
